# bf.toml
#
# Configuration for BrainF**k build
#
# (c) Andrew Shapton 2023
#

title = "BF build Configuration TOML file"

[BuildParameters]
sourceFile      = "bf.asm"          # Source assembler file                             (Required)
assembledFile   = "bf.exe"          # Output assembled executable file                  (Required)
prefix          = "BF"              # Prefix for the blocks                             (Required)
base            = "00200"            # Base adress for origination/load of executable    (Required)
title           = "BrainF**k"       # Title of program for Virtual Sphere               (Required)
vcass           = "bf"              # Filename for binary Virtual Sphere cassette       
js              = "bf"              # Filename for Javascript Virtual Sphere cassette   
cassette        = "bf"              # Filename for .wav file for cassette audio         

# (Un)comment flags as required
flags           = [
                    "noheader",     # Don't generate a Javascript header for the Virtual Sphere
                    "movebin",      # Move the binary to the assets location post-build
                    "silent"        # Don't produce any output (except errors)
]
[Locations]
convertEXEDir   = "/PATH/TO/CONVERT/EXE/WITH/TRAILING/SLASH/"              # Location of convertEXE file
srcDir          = "/PATH/TO/ASSEMBLER/SOURCE/CODE/WITH/TRAILING/SLASH/"    # Location of assembler source code
outputDir       = "/PATH/TO/OUTPUT/DIRECTORY/WITH/TRAILING/SLASH/"         # Location of target assets

[Miscellaneous]
buildASM        = "build.asm"       # Name of build file (with version etc inside)
buildJustify    = "L"               # Justify property for build version -  C - Centre Justified [Default]
                                    #                                       L - Left Justified
                                    #                                       R - Right Justified
NLAfterBuildVersion = true          # true to place a new line after the build version [Default]
                                    # false for no new line
                                    # NOTE - MUST BE LOWER CASE
