# config.toml
#
# Configuration for this build
#
# (c) Andrew Shapton 2023
#

title = "This build's configuration"

[Config]
build       = "src/build.toml"  # Generic Settings
this        = "src/bf.toml"     # Build specific settings
symbolstruct = "src/symbols.toml"        # Symbol Structure file